services:
  abbt: 
    image: ${IMAGE}
    ports:
      - "9898:9898"
    privileged: true
  # web:
  # # resue service config in another docker compose file
  #   extends:
  #     file: common-services.yml
  #     service: webapp
  #   environment:
  #     - DEBUG=1
  #   cpu_shares: 5
  #   depends_on:
  #     - db
  #   privileged: true
  #   volumes:
  #       - /var/lib/postgresql/data
  #   command: python otherapp.py
  #   # Expose ports without publishing them to the host machine - they’ll only be accessible to linked services. Only the internal port can be specified.
  #   expose:
  #     - 1234
  #   # servicename:alias -> in web -> ping db = ping database
  #   links:
  #     - "db:database"
  #   restart: always

